/*
 * THIS FILE IS GENERATED BY EMBEDBLOCKS STUDIO.
 * Wrapper header for PlatformIO compatibility.
 * Generated for: STM32F301K6
 */
#pragma once

// Include the actual variant header
// Using variant_generic.h as default for generic STM32 boards
#include "variant_generic.h"
