/* Auto-generated by EmbedBlocks */

#include <Arduino.h>

void setup() {
  pinMode(PA0, OUTPUT);
  pinMode(PA1, OUTPUT);
}

void loop() {
  digitalWrite(PA0, HIGH);
  delay(1000);
  analogWrite(PA1, 255);

}
