[env:eb_custom_board]
platform = ststm32
board = eb_custom_board
framework = arduino
board_build.variants_dir = variants
board_build.variant = eb_custom_variant
build_flags = -DSTM32WB15xx
extra_scripts = post:fix_wb_build.py
