/* Auto-generated by EmbedBlocks */

#include <Arduino.h>

// Globals
bool toggleState_PA0 = false;

void setup() {
  pinMode(PA0, OUTPUT);
}

void loop() {
  toggleState_PA0 = !toggleState_PA0;
  digitalWrite(PA0, toggleState_PA0 ? HIGH : LOW);
  delay(1000);

}
