# fix_l1_variant.py (Auto-generated by EmbedBlocks Studio)
import os
Import("env")

variant_cpp = os.path.join(env.subst("$PROJECT_DIR"), "variants", "eb_custom_variant", "variant_generic.cpp")
if os.path.exists(variant_cpp):
    with open(variant_cpp, "r", encoding="utf-8") as f:
        content = f.read()

    # 将未定义的引脚替换为 NC (Not Connected)
    bad_pins = ["PF_11", "PF_12", "PF_13", "PF_14", "PF_15", "PG_13", "PG_14", "PH_3", "PF_11,"]
    for pin in bad_pins:
        content = content.replace(f"  {pin},", f"  NC, // {pin} removed")

    with open(variant_cpp, "w", encoding="utf-8") as f:
        f.write(content)
