/**
 * ============================================================
 * 代码构建器 (CodeBuilder)
 * ============================================================
 * 
 * 用于结构化、模块化地生成 C++/Arduino 代码。
 * 
 * 痛点背景:
 * 传统的积木代码生成往往采用简单的字符串拼接。在处理复杂硬件积木时，
 * 经常会出现 `#include` 冲突、全局变量缺失、初始化顺序错误等问题。
 * 
 * 解决方案:
 * CodeBuilder 将代码划分为不同的段（Sections），每个积木块只需声明它
 * 需要的“副作用”（如添加一个头文件或在 setup 中初始化）。
 * 构建器会在最后阶段统一进行去重、排序并在正确的 C++ 语法位置插入代码。
 * 
 * 代码拼接顺序 (Final Assembly Order):
 * 1. Includes (#include 语句 - 编译预处理)
 * 2. Macros (#define 宏定义)
 * 3. Types (struct/enum 类型定义)
 * 4. Globals (全局变量/对象实例化)
 * 5. Prototypes (函数原型声明 - 解决循环调用)
 * 6. setup() 函数 (硬件初始化)
 * 7. loop() 函数 (主循环逻辑)
 * 8. Functions (用户自定义函数体)
 */

/**
 * 核心代码构建类
 */
export class CodeBuilder {
    // 使用 Set 确保头文件绝对不重复
    private includes: Set<string> = new Set();
    
    // 使用 Map 利用 Key 进行语义化去重 (如果两个积木添加了同一个 Key 的定义，则只保留一份)
    private macros: Map<string, string> = new Map();
    private types: Map<string, string> = new Map();
    private globals: Map<string, string> = new Map();
    private prototypes: Map<string, string> = new Map();
    private setups: Map<string, string> = new Map();
    private loops: Map<string, string> = new Map();
    private functions: Map<string, string> = new Map();

    /**
     * 添加包含文件 (Add Include)
     * e.g. addInclude('wifi_h', '#include <WiFi.h>')
     */
    public addInclude(key: string, code: string) {
        this.includes.add(code);
    }

    /**
     * 添加宏定义 (Add Macro)
     * e.g. addMacro('version', '#define VER 1.0')
     */
    public addMacro(key: string, code: string) {
        this.macros.set(key, code);
    }

    /**
     * 添加类型定义 (Add Type/Struct/Enum)
     */
    public addType(key: string, code: string) {
        this.types.set(key, code);
    }

    /**
     * 添加全局变量或对象定义
     * e.g. addVariable('led_pin', 'int led = 13;')
     */
    public addVariable(key: string, code: string) {
        this.globals.set(key, code);
    }

    /**
     * 添加函数原型 (为 C++ 编译提供前置声明)
     */
    public addPrototype(key: string, code: string) {
        this.prototypes.set(key, code);
    }

    /**
     * 添加 Setup 初始化代码
     * 这些代码会被放置在 void setup() { ... } 内部。
     */
    public addSetup(key: string, code: string) {
        this.setups.set(key, code);
    }

    /**
     * 添加 Loop 处理代码
     * 这些代码会被放置在 void loop() { ... } 内部。
     */
    public addLoop(key: string, code: string) {
        this.loops.set(key, code);
    }

    /**
     * 添加完整的函数定义
     */
    public addFunction(key: string, code: string) {
        this.functions.set(key, code);
    }

    /**
     * 核心构建逻辑：执行最终的代码拼接
     * 
     * @param userSetupCode 积木工作区生成的 Setup 部分主逻辑
     * @param userLoopCode 积木工作区生成的 Loop 部分主逻辑
     * @param indent 缩进风格，默认 2 空格
     * @returns 完整的、可编译的 C++ 源代码字符串
     */
    public build(userSetupCode: string = '', userLoopCode: string = '', indent: string = '  '): string {
        const lines: string[] = [];

        lines.push('/* Auto-generated by EmbedBlocks Studio */\n');

        // 1. 包含文件
        if (this.includes.size > 0) {
            lines.push([...this.includes].join('\n'));
            lines.push('');
        }

        // 2. 宏定义
        if (this.macros.size > 0) {
            lines.push('// Macros');
            lines.push([...this.macros.values()].join('\n'));
            lines.push('');
        }

        // 3. 类型定义
        if (this.types.size > 0) {
            lines.push('// Types');
            lines.push([...this.types.values()].join('\n'));
            lines.push('');
        }

        // 4. 全局变量
        if (this.globals.size > 0) {
            lines.push('// Globals');
            lines.push([...this.globals.values()].join('\n'));
            lines.push('');
        }

        // 5. 函数原型
        if (this.prototypes.size > 0) {
            lines.push('// Function Prototypes');
            lines.push([...this.prototypes.values()].join('\n'));
            lines.push('');
        }

        /** 
         * 智能缩进辅助函数：
         * 确保每行代码都有正确的层级缩进，且不重复缩进已有格式。
         */
        const smartIndent = (fragment: string) => {
            if (!fragment) return '';
            return fragment.split('\n').map(l => {
                if (!l.trim()) return l; 
                if (l.startsWith(indent)) return l; 
                return indent + l;
            }).join('\n');
        };

        // 6. 构造 setup() 函数体
        lines.push('void setup() {');
        const setupBody: string[] = [];
        this.setups.forEach(code => setupBody.push(code));
        if (userSetupCode && userSetupCode.trim()) setupBody.push(userSetupCode);

        setupBody.forEach(fragment => {
            const indented = smartIndent(fragment);
            if (indented) lines.push(indented);
        });
        lines.push('}\n');

        // 7. 构造 loop() 函数体
        lines.push('void loop() {');
        const loopBody: string[] = [];
        this.loops.forEach(code => loopBody.push(code));
        if (userLoopCode && userLoopCode.trim()) loopBody.push(userLoopCode);

        loopBody.forEach(fragment => {
            const indented = smartIndent(fragment);
            if (indented) lines.push(indented);
        });
        lines.push('}\n');

        // 8. 放置函数体
        if (this.functions.size > 0) {
            lines.push('// Functions');
            lines.push([...this.functions.values()].join('\n\n'));
        }

        return lines.join('\n');
    }

    /**
     * 获取构建器状态快照 (getSnapshot)
     * 【重点】：该方法是积木校验系统的基石。它允许我们将所有待编译的“副作用”
     * 封装进 JSON 格式，以便在后续的 Headless 编译流程中重建项目。
     */
    public getSnapshot() {
        return {
            includes: Array.from(this.includes),
            macros: Array.from(this.macros.values()),
            types: Array.from(this.types.values()),
            globals: Array.from(this.globals.values()),
            prototypes: Array.from(this.prototypes.values()),
            setups: Array.from(this.setups.values()),
            loops: Array.from(this.loops.values()),
            functions: Array.from(this.functions.values())
        };
    }

    /**
     * 重置构建器容器，为下一次代码生成任务清空状态。
     */
    public reset() {
        this.includes.clear();
        this.macros.clear();
        this.types.clear();
        this.globals.clear();
        this.prototypes.clear();
        this.setups.clear();
        this.loops.clear();
        this.functions.clear();
    }
}
