/**
 * 代码构建器类 (CodeBuilder Class)
 * 
 * 用于结构化、模块化地生成 C++ / Arduino 代码。
 * 解决简单的字符串拼接难以处理 Include 冲突、全局变量顺序和 Setup/Loop 初始化顺序的问题。
 */
export class CodeBuilder {
    private includes: Set<string> = new Set();
    private macros: Map<string, string> = new Map();
    private types: Map<string, string> = new Map();
    private globals: Map<string, string> = new Map();
    private prototypes: Map<string, string> = new Map();
    private setups: Map<string, string> = new Map();
    private loops: Map<string, string> = new Map();
    private functions: Map<string, string> = new Map();

    /**
     * 添加包含文件 (Add Include)
     */
    public addInclude(key: string, code: string) {
        this.includes.add(code);
    }

    /**
     * 添加宏定义 (Add Macro)
     */
    public addMacro(key: string, code: string) {
        this.macros.set(key, code);
    }

    /**
     * 添加类型定义 (Add Type/Struct/Enum)
     */
    public addType(key: string, code: string) {
        this.types.set(key, code);
    }

    /**
     * 添加全局变量 (Add Global Variable)
     */
    public addVariable(key: string, code: string) {
        this.globals.set(key, code);
    }

    /**
     * 添加函数原型 (Add Function Prototype)
     */
    public addPrototype(key: string, code: string) {
        this.prototypes.set(key, code);
    }

    /**
     * 添加 Setup 初始化代码 (Add Setup Code)
     */
    public addSetup(key: string, code: string) {
        this.setups.set(key, code);
    }

    /**
     * 添加 Loop 处理代码 (Add Loop Code)
     */
    public addLoop(key: string, code: string) {
        this.loops.set(key, code);
    }

    /**
     * 添加函数定义 (Add Function Definition)
     */
    public addFunction(key: string, code: string) {
        this.functions.set(key, code);
    }

    /**
     * 生成最终代码内容 (Build Final Code)
     */
    public build(userSetupCode: string = '', userLoopCode: string = '', indent: string = '  '): string {
        const lines: string[] = [];

        lines.push('/* Auto-generated by EmbedBlocks */\n');

        // 1. Includes
        if (this.includes.size > 0) {
            lines.push([...this.includes].join('\n'));
            lines.push('');
        }

        // 2. Macros
        if (this.macros.size > 0) {
            lines.push('// Macros');
            lines.push([...this.macros.values()].join('\n'));
            lines.push('');
        }

        // 3. Types
        if (this.types.size > 0) {
            lines.push('// Types');
            lines.push([...this.types.values()].join('\n'));
            lines.push('');
        }

        // 4. Globals
        if (this.globals.size > 0) {
            lines.push('// Globals');
            lines.push([...this.globals.values()].join('\n'));
            lines.push('');
        }

        // 5. Prototypes
        if (this.prototypes.size > 0) {
            lines.push('// Function Prototypes');
            lines.push([...this.prototypes.values()].join('\n'));
            lines.push('');
        }

        // Helper to indent lines safely
        const smartIndent = (fragment: string) => {
            if (!fragment) return '';
            return fragment.split('\n').map(l => {
                if (!l.trim()) return l; // Preserve empty lines
                if (l.startsWith(indent)) return l; // Avoid double indentation
                return indent + l;
            }).join('\n');
        };

        // 6. Setup
        lines.push('void setup() {');
        const setupBody: string[] = [];
        this.setups.forEach(code => setupBody.push(code));
        if (userSetupCode && userSetupCode.trim()) setupBody.push(userSetupCode);

        setupBody.forEach(fragment => {
            const indented = smartIndent(fragment);
            if (indented) lines.push(indented);
        });
        lines.push('}\n');

        // 7. Loop
        lines.push('void loop() {');
        const loopBody: string[] = [];
        this.loops.forEach(code => loopBody.push(code));
        if (userLoopCode && userLoopCode.trim()) loopBody.push(userLoopCode);

        loopBody.forEach(fragment => {
            const indented = smartIndent(fragment);
            if (indented) lines.push(indented);
        });
        lines.push('}\n');

        // 8. Functions
        if (this.functions.size > 0) {
            lines.push('// Functions');
            lines.push([...this.functions.values()].join('\n\n'));
        }

        return lines.join('\n');
    }

    /**
     * 重置构建器 (Reset for next run if needed)
     */
    public reset() {
        this.includes.clear();
        this.macros.clear();
        this.types.clear();
        this.globals.clear();
        this.prototypes.clear();
        this.setups.clear();
        this.loops.clear();
        this.functions.clear();
    }
}
