[env:STM32WLE5CC]
platform = ststm32
board = eb_custom_board
framework = arduino
board_build.variants_dir = variants
board_build.variant = eb_custom_variant
build_flags = -DSTM32WLE5xx
extra_scripts = pre:fix_wl_build.py
